spring:
  application:
        name: Deals_Coupen_Finder_App_JWTService
  data:
    mongodb:
      uri: mongodb+srv://nihal:12345@cluster0.c40tict.mongodb.net/UserDatabase?retryWrites=true&w=majority  
             
jwt:
  secret: secrectkey123
  

server:
 port: 8081
eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka

logging:
  file: 
    path: /my-logs/app.log
    name: log.txt
data:
  exception:
        incmsg: Invalid Credentials!!