server: 
  port: 8080
  
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/
     
spring:
 application:
  name: APIGateWayService
 cloud:
  gateway:
   routes:
    - id: Deals_Coupen_Finder_App_JWTService
      uri: http://localhost:8081/
      predicates:
      - Path=/api/jwt/**
      
      
    - id: DealsService
      uri: http://localhost:9091/
      predicates:
       - Path=/api/d1/**
    - id: DealsServiceUser
      uri: http://localhost:9092/
      predicates:
       - Path=/api/d1/**
    
      
    - id: CouponService
      uri: http://localhost:9093/
      predicates:
       - Path=/api/c1/** 
    - id: CouponServiceUser
      uri: http://localhost:9094/
      predicates:
       - Path=/api/c2/** 
        
logging:
  file: 
    path: /my-logs/app.log
    name: log.txt       